import { escapeHtml as e, icon, money, notice, showDetails } from '../components.js?v=3';
import { db, fail } from '../backend-ui.js';
const DAY=86400000, key=d=>new Date(d).toISOString().slice(0,10), plus=(d,n)=>key(new Date(new Date(d+'T12:00:00Z').getTime()+n*DAY));
const weekStart=d=>{const x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()-((x.getUTCDay()+6)%7));return key(x)};
const day=d=>new Intl.DateTimeFormat('en-PH',{weekday:'short',month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
const shortDay=d=>new Intl.DateTimeFormat('en-PH',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(d+'T12:00:00Z'));
const time=t=>t?new Intl.DateTimeFormat('en-PH',{hour:'numeric',minute:'2-digit',timeZone:'UTC'}).format(new Date('1970-01-01T'+t+'Z')):'Time TBD';
const localSlotTime=value=>new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Asia/Manila'}).format(new Date(value));
const delivery=x=>x==='lalamove'?'Delivery':'Pickup', tone=x=>({pending:'pending',confirmed:'confirmed',preparing:'preparing',ready:'ready',completed:'ready',cancelled:'cancelled'}[x]||'pending');
const payment=x=>({unpaid:'Downpayment Pending',partially_paid:'60% Downpayment Paid',paid:'Fully Paid',failed:'Payment Failed',refunded:'Refunded'}[x]||String(x||'Unpaid').replaceAll('_',' '));
const attention=x=>x.status==='pending'||x.payment_status==='unpaid'||Boolean(x.customization_summary), product=x=>(x||'Order').split(',')[0].replace(/\s×\d+$/,'').trim();

export async function renderBookings(content){
 let selected='2026-09-21',start=weekStart(selected),view='week',filter='all',search='',entries=[],settings=new Map(),hoverTimer,hideTimer;
 const days=()=>Array.from({length:7},(_,i)=>plus(start,i)), rows=d=>entries.filter(x=>x.booking_date===d);
 const summary=d=>{const list=rows(d),setting=settings.get(d),capacity=setting?.capacity||list[0]?.capacity||6,active=list.filter(x=>x.status!=='cancelled'),closed=!!(setting?.is_closed||list[0]?.is_closed);return {list,capacity,active,closed,pickup:active.filter(x=>x.fulfillment_method==='pickup').length,delivery:active.filter(x=>x.fulfillment_method==='lalamove').length};};
 const state=s=>s.closed?'closed':s.active.length>=s.capacity?'full':s.active.length===s.capacity-1?'near':'available';
 const matches=x=>(!search||`${x.customer_name} ${x.order_reference} ${x.order_summary}`.toLowerCase().includes(search))&&(filter==='all'||filter==='pickup'&&x.fulfillment_method==='pickup'||filter==='lalamove'&&x.fulfillment_method==='lalamove'||filter==='attention'&&attention(x));
 const select=d=>{selected=d;start=weekStart(d)};
 const range=()=>{if(view==='week')return [start,plus(start,6)];const d=new Date(selected+'T12:00:00Z');return [key(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1))),key(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)))];};
 async function load(){content.innerHTML=notice('Loading booking schedule…');const [from,to]=range();try{const [schedule,settingResult]=await Promise.all([db.rpc('get_booking_schedule',{from_date:from,to_date:to}),db.client.from('booking_date_settings').select('booking_date,capacity,is_closed,closed_reason').gte('booking_date',from).lte('booking_date',to)]);if(settingResult.error)throw settingResult.error;entries=schedule;settings=new Map(settingResult.data.map(x=>[x.booking_date,x]));draw();}catch(error){fail(content,error);}}
 function mini(){const f=new Date(selected+'T12:00:00Z'),first=new Date(Date.UTC(f.getUTCFullYear(),f.getUTCMonth(),1)),grid=new Date(first);grid.setUTCDate(first.getUTCDate()-first.getUTCDay());return `<section class="booking-mini"><header><button data-month="-1" aria-label="Previous month">‹</button><strong>${f.toLocaleString('en-PH',{month:'long',year:'numeric',timeZone:'UTC'})}</strong><button data-month="1" aria-label="Next month">›</button></header><div class="booking-mini__week">${['S','M','T','W','T','F','S'].map(x=>`<span>${x}</span>`).join('')}</div><div class="booking-mini__dates">${Array.from({length:42},(_,i)=>plus(key(grid),i)).map(d=>{const s=summary(d),t=state(s),outside=new Date(d+'T12:00:00Z').getUTCMonth()!==f.getUTCMonth();return `<button data-mini="${d}" class="${d===selected?'selected':''} ${outside?'outside':''} ${t}" title="${t==='closed'?'Admin Closed':`${s.active.length} / ${s.capacity} bookings`}">${new Date(d+'T12:00:00Z').getUTCDate()}</button>`}).join('')}</div></section>`}
 function header(d){const s=summary(d),t=state(s),used=s.active.length,p=Math.min(100,Math.round(100*used/s.capacity)),label=t==='closed'?'Admin Closed':t==='full'?'Fully Booked':t==='near'?'Almost Full':'Available';return `<button data-date="${d}" class="booking-day ${d===selected?'selected':''} ${t}"><b>${shortDay(d)}</b><span class="capacity-number"><i></i>${used} / ${s.capacity}</span><span class="capacity-progress"><i style="width:${p}%"></i></span><small>${t==='closed'?`${icon('lock')} Closed`:label}</small></button>`}
 function card(x){const [h=8,m=0]=(x.scheduled_start||'08:00').split(':').map(Number),same=rows(x.booking_date).filter(y=>y.scheduled_start===x.scheduled_start&&matches(y)).indexOf(x),top=Math.max(5,(h-8)*66+(m/60)*66+5+same*17);return `<button data-booking="${x.id}" class="booking-card status-${tone(x.status)} ${x.status==='cancelled'?'cancelled':''}" style="top:${top}px"><span class="booking-status-dot" title="${e(x.status)}"></span><b>${e(x.customer_name)}</b><small>#${e(x.order_reference)}</small><span>${e(product(x.order_summary))}</span><em class="fulfillment ${x.fulfillment_method==='lalamove'?'delivery':''}">${x.fulfillment_method==='lalamove'?icon('delivery'):icon('bookings')}${delivery(x.fulfillment_method)}</em></button>`}
 function sidebar(){const s=summary(selected),t=state(s),used=s.active.length,remaining=Math.max(0,s.capacity-used),label=t==='closed'?'Admin Closed':t==='full'?'Fully Booked':t==='near'?'Almost Full':'Available';return `${mini()}<section class="booking-selected-card ${t}"><header>${icon(t==='closed'?'lock':'bookings')}<div><strong>${day(selected)}</strong><small>${label}</small></div></header><div class="booking-capacity"><div><strong>${used} / ${s.capacity} bookings</strong><span class="booking-state ${t}">${label}</span></div><progress max="${s.capacity}" value="${used}"></progress><small>${t==='closed'?'No new customer bookings':`${remaining} slot${remaining===1?'':'s'} remaining`}</small><div class="booking-counts"><span>${icon('bookings')} ${s.pickup} Pickup</span><span>${icon('delivery')} ${s.delivery} Delivery</span></div></div></section><section class="booking-today"><h2>Selected-Day Bookings <button data-all>View all</button></h2>${s.list.length?s.list.sort((a,b)=>(a.scheduled_start||'99').localeCompare(b.scheduled_start||'99')).map(x=>`<button data-booking="${x.id}"><b>${time(x.scheduled_start)}</b><span>${e(product(x.order_summary))}<small>#${e(x.order_reference)}</small></span><em class="${x.fulfillment_method==='lalamove'?'delivery':''}">${delivery(x.fulfillment_method)}</em></button>`).join(''):'<p class="booking-empty">No bookings for this date.</p>'}</section><button class="button booking-close ${t==='closed'?'reopen':''}" data-close>${t==='closed'?`${icon('arrow')} Reopen date`:`${icon('lock')} Close date`}</button>`}
 function week(){return `<div class="booking-reference-layout"><section class="booking-calendar"><div class="booking-days"><span></span>${days().map(header).join('')}</div><div class="booking-time-grid"><div class="booking-hours">${Array.from({length:10},(_,i)=>`<span>${time(String(i+8).padStart(2,'0')+':00')}</span>`).join('')}</div>${days().map(d=>`<div class="booking-column">${Array.from({length:10},(_,i)=>`<button class="booking-hour" data-availability-time="${d}|${String(i+8).padStart(2,'0')}:00" aria-label="Block time on ${day(d)} at ${time(String(i+8).padStart(2,'0')+':00')}"></button>`).join('')}${rows(d).filter(matches).map(card).join('')}</div>`).join('')}</div><aside class="booking-preview" hidden></aside></section><aside class="booking-side">${sidebar()}</aside></div>`}
 function month(){const [from,to]=range(),f=new Date(from+'T12:00:00Z'),grid=new Date(f);grid.setUTCDate(f.getUTCDate()-f.getUTCDay());return `<div class="booking-month-view">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<b>${x}</b>`).join('')}${Array.from({length:42},(_,i)=>plus(key(grid),i)).map(d=>{const s=summary(d),t=state(s),outside=d<from||d>to;return `<button data-month-date="${d}" class="month-day ${t} ${outside?'outside':''} ${d===selected?'selected':''}"><strong>${new Date(d+'T12:00:00Z').getUTCDate()}</strong><span>${s.active.length} / ${s.capacity}</span><i>${t==='closed'?'Admin Closed':t==='full'?'Fully Booked':t==='near'?'Almost Full':'Available'}</i></button>`}).join('')}</div>`}
 function draw(){content.innerHTML=`<header class="module-heading booking-heading"><div><h1>${view==='week'?'Booking Schedule':'Booking Capacity Month'}</h1><p>Manage and monitor customer pickup and delivery schedules.</p></div></header><div class="booking-topbar"><div class="booking-view-toggle"><button data-view="week" class="${view==='week'?'active':''}">Week</button><button data-view="month" class="${view==='month'?'active':''}">Month</button></div><button class="button icon-only" data-prev aria-label="Previous period">‹</button><button class="button icon-only" data-next aria-label="Next period">›</button><button data-today hidden></button><button class="button primary" data-add>${icon('plus')} Add Booking</button><div class="booking-filter-row"><span>Filters:</span>${[['all','All'],['pickup','Pickup'],['lalamove','Delivery'],['attention','Needs Attention']].map(([id,label])=>`<button data-filter="${id}" class="${filter===id?'active':''}">${label}</button>`).join('')}<label class="booking-search">${icon('search')}<input type="search" placeholder="Search bookings…" value="${e(search)}"></label></div></div>${view==='week'?week():month()}`;bind()}
 function bind(){content.querySelector('.booking-search input').oninput=ev=>{search=ev.target.value.toLowerCase();draw()};content.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;load()});content.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;draw()});content.querySelectorAll('[data-date],[data-mini]').forEach(b=>b.onclick=()=>{select(b.dataset.date||b.dataset.mini);if(view==='month')view='week';load()});content.querySelectorAll('[data-month-date]').forEach(b=>b.onclick=()=>{select(b.dataset.monthDate);view='week';load()});content.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{const d=new Date(selected+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+Number(b.dataset.month));select(key(d));load()});content.querySelector('[data-prev]').onclick=()=>{if(view==='week')select(plus(start,-7));else{const d=new Date(selected+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()-1);select(key(d))}load()};content.querySelector('[data-next]').onclick=()=>{if(view==='week')select(plus(start,7));else{const d=new Date(selected+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);select(key(d))}load()};content.querySelector('[data-today]').onclick=()=>{select(key(new Date()));view='week';load()};content.querySelector('[data-all]')?.addEventListener('click',()=>{filter='all';draw()});content.querySelectorAll('[data-availability-time]').forEach(cell=>cell.onclick=()=>{const [date,startTime]=cell.dataset.availabilityTime.split('|');select(date);const hour=Number(startTime.slice(0,2));manage(startTime,`${String(Math.min(hour+1,23)).padStart(2,'0')}:00`)});content.querySelectorAll('[data-booking]').forEach(b=>{const x=entries.find(row=>row.id===b.dataset.booking);b.onclick=()=>details(x,b);b.onmouseenter=()=>{if(matchMedia('(hover:hover)').matches){clearTimeout(hideTimer);hoverTimer=setTimeout(()=>preview(x,b),260)}};b.onmouseleave=()=>{clearTimeout(hoverTimer);hideTimer=setTimeout(()=>{if(!content.querySelector('.booking-preview:hover'))hide()},140)}});const pop=content.querySelector('.booking-preview');if(pop){pop.onmouseenter=()=>clearTimeout(hideTimer);pop.onmouseleave=()=>hideTimer=setTimeout(hide,100)}content.querySelector('[data-close]')?.addEventListener('click',async()=>{const s=summary(selected);try{await db.rpc('save_booking_date_setting',{payload:{booking_date:selected,capacity:s.capacity,is_closed:!s.closed,closed_reason:!s.closed?'Closed by Admin':''}});load()}catch(error){alert(error.message)}});content.querySelector('[data-add]').onclick=add}
 function hide(){content.querySelector('.booking-preview')?.setAttribute('hidden','')}
 function preview(x,b){const pop=content.querySelector('.booking-preview'),box=b.getBoundingClientRect(),host=content.querySelector('.booking-calendar').getBoundingClientRect(),balance=x.order_total==null?null:Number(x.order_total)-Number(x.amount_paid||0);pop.innerHTML=`<button class="preview-close" aria-label="Close preview">×</button><header><span>${e(x.customer_name).slice(0,1)}</span><div><h2>${e(x.customer_name)}</h2><small>#${e(x.order_reference)}</small></div><em class="status-badge ${tone(x.status)}">${e(x.status)}</em></header><dl><dt>Date</dt><dd>${day(x.booking_date)}</dd><dt>Time</dt><dd>${time(x.scheduled_start)} – ${time(x.scheduled_end)}</dd><dt>Type</dt><dd>${delivery(x.fulfillment_method)}</dd><dt>Products</dt><dd>${e(x.order_summary)}</dd><dt>Customization</dt><dd>${e(x.customization_summary||'None')}</dd><dt>Payment</dt><dd>${e(payment(x.payment_status))}${balance!==null?` · ${money(balance)} remaining`:''}</dd><dt>Contact</dt><dd>${e(x.customer_contact||'No contact saved')}</dd></dl><button class="button primary" data-preview>View Full Booking ${icon('arrow')}</button>`;pop.hidden=false;pop.style.left=`${Math.max(8,Math.min(box.left-host.left+12,host.width-400))}px`;pop.style.top=`${Math.max(92,Math.min(box.top-host.top+8,host.height-390))}px`;pop.querySelector('[data-preview]').onclick=()=>details(x,b);pop.querySelector('.preview-close').onclick=hide}
 function details(x,b){hide();const allowed={pending:['confirmed','cancelled'],confirmed:['preparing','cancelled'],preparing:['ready','cancelled'],ready:['completed','cancelled']}[x.status]||[],dialog=showDetails(x.order_reference,`<div class="booking-detail"><header><h3>${e(x.customer_name)}</h3><span class="status-badge ${tone(x.status)}">${e(x.status)}</span></header><p>${e(x.customer_contact||'No contact saved')}</p><dl><dt>Type</dt><dd>${delivery(x.fulfillment_method)}</dd><dt>Date & time</dt><dd>${day(x.booking_date)} · ${time(x.scheduled_start)}–${time(x.scheduled_end)}</dd><dt>Products</dt><dd>${e(x.order_summary)}</dd><dt>Customization</dt><dd>${e(x.customization_summary||'None')}</dd><dt>Payment</dt><dd>${e(payment(x.payment_status))}</dd><dt>Booking status</dt><dd>${e(x.status)}</dd></dl>${allowed.map(s=>`<button class="button" data-booking-status="${s}">Mark ${s}</button>`).join('')}${x.order_id?`<a class="button primary" href="#orders/detail/${x.order_id}">View Full Order</a>`:''}<p role="alert"></p></div>`,b);dialog.querySelectorAll('[data-booking-status]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await db.rpc(x.order_id?'set_order_status':'update_booking_status',x.order_id?{order_id:x.order_id,next_status:button.dataset.bookingStatus}:{target:x.id,next_status:button.dataset.bookingStatus});dialog.close();await load()}catch(error){dialog.querySelector('[role=alert]').textContent=error.message;button.disabled=false}})}
 async function manage(pauseFrom='',pauseTo=''){const date=selected,from=date+'T00:00:00+08:00',to=plus(date,1)+'T00:00:00+08:00';try{const result=await db.client.from('availability_slots').select('starts_at,ends_at,is_open').gte('starts_at',from).lt('starts_at',to).order('starts_at');if(result.error)throw result.error;const active=result.data.filter(x=>x.is_open),opening=active[0]?localSlotTime(active[0].starts_at):'08:00',closing=active.length?localSlotTime(active.at(-1).ends_at):'17:00';const dialog=showDetails('Manage Availability',`<form class="booking-availability-form"><p class="availability-date">${day(date)}</p><label>Operating hours <span><input name="opening_time" type="time" value="${opening}" required> — <input name="closing_time" type="time" value="${closing}" required></span></label><hr><h3>Temporarily Close Time</h3><label>From <input name="pause_from" type="time" value="${pauseFrom}"></label><label>To <input name="pause_to" type="time" value="${pauseTo}"></label><label>Reason <input name="reason" maxlength="300" placeholder="Lunch break"></label><p class="availability-note">Closing a time creates receiving windows before and after it. Existing orders remain unchanged.</p><p role="alert"></p><button class="button primary">Save Availability</button></form>`,null);dialog.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const button=ev.currentTarget.querySelector('button');button.disabled=true;try{await db.rpc('manage_booking_availability',{payload:{booking_date:date,...Object.fromEntries(new FormData(ev.currentTarget))}});dialog.close();await load()}catch(error){dialog.querySelector('[role=alert]').textContent=error.message;button.disabled=false}}}catch(error){alert(error.message)}}
 function add(){const dialog=showDetails('Add Booking',`<form class="booking-form"><label>Customer<input name="customer_name" required></label><label>Contact<input name="customer_contact"></label><label>Order reference<input name="order_reference"></label><label>Products / order summary<input name="order_summary" required></label><label>Date<input name="booking_date" type="date" required value="${selected}"></label><label>Start time<input name="scheduled_start" type="time"></label><label>End time<input name="scheduled_end" type="time"></label><label>Fulfillment<select name="fulfillment_method"><option value="pickup">Pickup</option><option value="lalamove">Delivery</option></select></label><label>Status<select name="status"><option value="pending">Pending</option><option value="confirmed">Confirmed</option></select></label><p role="alert"></p><button class="button primary">Save booking</button></form>`,null);dialog.querySelector('form').onsubmit=async ev=>{ev.preventDefault();try{await db.rpc('create_booking',{payload:Object.fromEntries(new FormData(ev.currentTarget))});dialog.close();load()}catch(error){dialog.querySelector('[role=alert]').textContent=error.message}}}
 load()
}
